config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/link_through'
  	get '/home' => 'pages#home'
  	get '/index' => 'questions#index'
  	get '/privacy' => "pages#privacy"
	get '/user/:id' => 'pages#profile'
	get '/tag/:tag_id' => 'pages#tag', as: :tag
	get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
	get 'notifications/:id/view_all', to: 'notifications#view_all',
								        as: :view_all

	devise_for :users

	resources :questions do
	  	resources :answers
		put "upvote", to: "questions#upvote"
		put "downvote", to: "questions#downvote"
		put "undoupvote", to: "questions#undoupvote"
		put "undodownvote", to: "questions#undodownvote"
		put "star", to: "questions#star"
		put "unstar", to: "questions#unstar"
		put "resolved", to: "questions#resolved"
	end

	resources :answers do
		resources :questions
		put "upvote", to: "answers#upvote"
		put "downvote", to: "answers#downvote"
		put "undoupvote", to: "answers#undoupvote"
		put "undodownvote", to: "answers#undodownvote"
	end

  	# define the root to go to questions if user is signed in, home otherwise
	authenticated :user do
	  root :to => "questions#index"
	end
	root :to => redirect("/home")
	# catch any undefined routes and redirect to root page
	
	get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  	acts_as_votable
  	acts_as_taggable
	belongs_to :user
	has_many :answers
	has_many :notifications, dependent: :destroy
	validates :user_id, presence: true
	validates :headline, presence: true, length: { maximum: 150 }
	validates :content, presence: true

	validate :tag_size 
	def tag_size
	 self.tag_list.each do |tag|
	  errors[:tag_list] << "must only contain 3-letter departmental abbreviations" if tag.length != 3 
	 end
	end

	def self.tag_search(tag_id)
		if tag_id
			Question.tagged_with(tag_id)
		end
	end

	scope :term, -> (term) { where("headline ILIKE ? OR content ILIKE ?", "%#{term}%", "%#{term}%") | Question.tagged_with(term) }

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_owned_question, only: [:edit, :update, :destroy]

  # helper param for the sort_by() call in index method and create_notification in question_resolve
  helper_method :sort_param, :create_notification

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.where(nil) # creates an anonymous scope
    @questions = @questions.term(params[:term]) if params[:term].present?
    @search_term = params[:term] if params[:term].present?
    @questions = Question.find(current_user.starred) if params[:starred].present?
    @questions = @questions.sort_by { |m| m[sort_param] }.reverse if sort_param.present?
    @questions = Kaminari.paginate_array(@questions).page(params[:page]).per(20)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    if Question.exists?(params[:id])
      @question = Question.find(params[:id])
    else
      redirect_to questions_url
    end
    # to avoid NIL error
    @answer = Answer.new

  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)
    @question.anon = params[:anon]
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @question = Question.find(params[:question_id])
    @question.upvote_from current_user
    respond_to do |format|
      format.js
    end
  end

  def downvote
    @question = Question.find(params[:question_id])
    @question.downvote_from current_user
    respond_to do |format|
      format.js
    end
  end

  def undoupvote
    @question = Question.find(params[:question_id])
    @question.unliked_by current_user
    respond_to do |format|
      format.js
    end
  end

  def undodownvote
    @question = Question.find(params[:question_id])
    @question.undisliked_by current_user
    respond_to do |format|
      format.js
    end
  end

  def star
    @question = Question.find(params[:question_id])
    current_user.starred << params[:question_id]
    current_user.save(validate: false)
    respond_to do |format|
      format.js
    end
  end

  def unstar
    @question = Question.find(params[:question_id])
    current_user.starred.delete_if {|x| x==@question.id}
    current_user.save(validate: false)
    respond_to do |format|
      format.js
    end
  end

  def resolved
    @question = Question.find(params[:question_id])
    @question.resolved = true
    @question.save
    create_notification @question
    respond_to do |format|
      format.js
    end
  end

  def tag_cloud
    @tags = Question.tag_counts_on(:tags)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owned_question
      begin
        @question = current_user.questions.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        logger.info "======================================================"
        logger.info e
        logger.info "======================================================"
        flash[:notice] = "You don't have access to that."
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:headline, :content, :user_id, :tag_list, :anon)
    end

    # sanitize the ordering param
    def sort_param
      ["created_at", "cached_weighted_score"].include?(params[:sort]) ? params[:sort] : "cached_weighted_score"
    end

    # create notification for everyone who has the question starred
    def create_notification(question)
      @selected = User.where("?=ANY(starred)", question.id)
      @selected.each do |selected|
        Notification.create(user_id: selected.id,
                          notified_by_id: current_user.id,
                          question_id: question.id,
                          identifier: question.id,
                          notice_type: 'marked as resolved')
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h4>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :headline, "Question (one line summary)" %>
    <%= form.text_field :headline, id: :question_headline, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, "Details" %>
    <%= form.text_area :content, id: :question_content, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :tag_list, "Your tags (comma-separated)" %><br/>
    <%= form.text_field :tag_list, placeholder:"Currently restricted to 3-letter departmental abbreviations, (i.e. 'cos, mol, wws')", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= check_box_tag(:anon) %>
    <%= label_tag(:anon, "Submit anonymously (leave unchecked to show your netid)") %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Question", class:"btn btn-success"%>
  </div>
<% end %>

app/views/questions/_question.html.erb
<!-- displays a question in the table of all questions -->

<!-- right div: up/down arrows -->
<div style="float:right">
    <div> <!-- up arrow -->
        <% if current_user.voted_up_on? question %>
            <button class="btn btn-default btn-sm" disabled="true">
             <span class="glyphicon glyphicon-menu-up" aria-hidden="true" style="color:white"></span> 
             </button>  
        <% else %>
            <% if current_user.voted_down_on? question %>
                <%= button_to question_undodownvote_path(question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
                 <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>   
                <% end %>           
            <% else %>
                <%= button_to question_upvote_path(question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
                 <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>   
                <% end %>
            <% end %>
        <% end %>
    </div>

    <!-- current ranking -->
    <div class="text-center" style="font-size:16px;line-height: 22px;height: 22px;">
        <%= question.weighted_score %>
    </div>

    <div> <!-- down arrow -->
        <% if current_user.voted_down_on? question %>
            <button class="btn btn-default btn-sm" disabled="true">
                <span class="glyphicon glyphicon-menu-down" aria-hidden="true" style="color:white"></span>
            </button>   
        <% else %>
            <% if current_user.voted_up_on? question %>
                <%= button_to question_undoupvote_path(question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
                    <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>   
                <% end %>           
            <% else %>
                <%= button_to question_downvote_path(question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
                    <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>   
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>
<!-- left div: question -->
<div>
    <div class="pull-right" style="padding-right:10px;">
        <!-- display star -->
        <% if current_user.starred.include? (question.id) %>
            <!-- if question already starred, then show filled star. Click to unstar -->
            <%= link_to question_unstar_path(question), method: :put, remote: true do %><span class="glyphicon glyphicon-star" style="font-size:20px;color:#f4df42;"></span><% end %> 
        <% else %>
            <!-- if question not starred, then show empty star. Click to star -->
            <%= link_to question_star_path(question), method: :put, remote: true do %><span class="glyphicon glyphicon-star-empty" style="font-size:20px;color:#bfbdbc;"></span><% end %> 
        <% end %> 
    </div>
    <!-- display question headline -->
	<%= link_to question.headline, question, style:"text-decoration:none; font-weight:bold; font-size:16px; color:#404040;" %>
       <!-- if question is resolved, display green check mark -->
    <% if question.resolved %>
        <span class="glyphicon glyphicon-ok" style="color:#29b265; font-size:17px" aria-hidden="true"></span> 
    <% end %>
    <br>
    <!-- display how long ago the question was created-->
    <div class="grey-text" style="font-size: 12px;">
        <!-- when created and by whom (anon or no) -->
        <% if question.created_at > Time.now.beginning_of_day %>
            asked <%="#{time_ago_in_words(question.created_at)} ago"%> by 
            <% if question.anon %> 
                Anonymous
            <% else %>
                <%= User.find(question.user_id).username %>
            <% end %>
        <% else %>
            asked on <%= question.created_at.strftime("%b %d, %Y") %> by 
            <% if question.anon %> 
                Anonymous
            <% else %>
                <%= User.find(question.user_id).username %>
            <% end %>
        <% end %>
        <!-- how many answers -->
        <% if question.answers.size == 0 %>
            - <span style="color:#b53120">No answers</span>
        <% else %>
            <% if question.answers.size == 1 %>
                - 1 answer
            <% else %>
                - <%= question.answers.size %> answers
            <% end %>
        <% end %>
    </div>        

    <!-- display question content (first 75 chars) -->
    <span style="font-size:16px"><%= question.content.truncate(115) %></span>
  
    <p>            
      <% question.tag_list.each do |tag| %>
            <a href="/tag/<%=tag%>" class="label label-pill label-info" style="text-decoration:none;"><%= tag %></a>
      <% end %>
    </p>                                      
</div>

app/views/questions/_showquestion.html.erb
<!-- display the question -->
	<div class="panel-body">
		<!-- right div: up/down arrows -->
		<div style="float:right">
			<br><br>
		    <div> <!-- up arrow -->
		        <% if current_user.voted_up_on? @question %>
		            <button class="btn btn-default btn-sm" disabled="true">
		             <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> 
		             </button>  
		        <% else %>
		            <% if current_user.voted_down_on? @question %>
		                <%= button_to question_undodownvote_path(@question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
		                 <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>   
		                <% end %>           
		            <% else %>
		                <%= button_to question_upvote_path(@question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
		                 <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>   
		                <% end %>
		            <% end %>
		        <% end %>
			</div>

		    <!-- current ranking -->
		    <div class="text-center" style="font-size:16px;line-height: 22px;height: 22px;">
		        <%= @question.weighted_score %>
		    </div>

		    <div> <!-- down arrow -->
		        <% if current_user.voted_down_on? @question %>
		            <button class="btn btn-default btn-sm" disabled="true">
		                <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
		            </button>   
		        <% else %>
		            <% if current_user.voted_up_on? @question %>
		                <%= button_to question_undoupvote_path(@question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
		                    <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>   
		                <% end %>           
		            <% else %>
		                <%= button_to question_downvote_path(@question), class:"btn btn-default btn-sm", method: :put, remote: true do %>
		                    <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>   
		                <% end %>
		            <% end %>
		        <% end %>
		    </div>
		</div>
		<!-- left div: question information -->
		<div>
      		<div><span style="font-size:16px" class="glyphicon glyphicon-hand-left" aria-hidden="true"></span>
			 <%= link_to 'Back', questions_path, style:"font-size:16px" %> </div>
			 <br>
			<div class="pull-right" style="padding-right:10px;">
				<!-- display star -->
			    <% if current_user.starred.include? (question.id) %>
			        <!-- if question already starred, then show filled star. Click to unstar -->
			        <%= link_to question_unstar_path(question), method: :put, remote: true do %><span class="glyphicon glyphicon-star" style="font-size:24px;color:#f4df42;"></span><% end %> 
			    <% else %>
			        <!-- if question not starred, then show empty star. Click to star -->
			        <%= link_to question_star_path(question), method: :put, remote: true do %><span class="glyphicon glyphicon-star-empty" style="font-size:24px;color:#bfbdbc;"></span><% end %> 
			    <% end %> 
		    </div>

			<p>
			  <span style="font-size:20px"><b><%= @question.headline %></b></span>
			    <!-- if question is resolved, display green check mark -->
    			<% if @question.resolved %>
				    <span class="glyphicon glyphicon-ok" style="color:#29b265; font-size:20px" aria-hidden="true"></span> 
				<% end %>
			</p>
			<p>
			  <% @question.tag_list.each do |tag| %>
			  		<span class="label label-pill label-info"><%= tag %></span>
			  <% end %>
			</p>
			<p>
			  <span style="font-size:16px"><%= @question.content %></span>
			</p>
		</div>
	</div>
	<div class="panel-footer">
		<div>
			<% if user_signed_in? and current_user.owns_question?(@question) %>
				<% if !@question.resolved %>
					<%= link_to 'Mark as Resolved', question_resolved_path(@question), method: :put, remote: true %> |
				<% end %>
				<%= link_to 'Edit', edit_question_path(@question) %> |
				<%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
			<p class="pull-right text-muted">
				Updated 
				<span class="grey-text">
					<% if @question.created_at > Time.now.beginning_of_day %>
					    <%="#{time_ago_in_words(@question.created_at)} ago"%> 
					<% else %>
					    <%= @question.created_at.strftime("%b %d, %Y") %> 
					<% end %>
				</span>	
				by 
				<% if @question.anon %> 
					Anonymous
				<% else %>
					<%=User.find_by_id(@question.user_id).username%>
				<% end %>
			</p>
			<br>
		</div>
    </div>

app/views/questions/downvote.js.erb
$("#question_<%= @question.id %>").html("<%= escape_javascript(render partial: "questions/question", locals: {question: @question}) %>");
$("#question_shown").html("<%= escape_javascript(render partial: "questions/showquestion", locals: {question: @question}) %>");

app/views/questions/edit.html.erb
<body>
    <%= render '/layouts/nav' %>
    <div class="container"> 
    	<!-- left hand side layout -->
        <div class="col-md-8"> 
    		<div class="panel panel-default">
    			<div class="panel-body">
    				<div><span style="font-size:16px" class="glyphicon glyphicon-hand-left" aria-hidden="true"></span>
    				 <%= link_to 'Back', @question, style:"font-size:16px" %> </div>
    			 <br>
    				<h4>Editing Question</h4>
    				<%= render 'form', question: @question %>
    				<br>
    			</div>
    		</div>
        </div>

        <!-- right hand side layout -->
        <div class="col-md-4"> 
        	<!-- container for user info -->
            <div class="panel panel-default">
                <br>
                <div class="panel-body">
                    <h4>Welcome, <b><%= current_user.username %>@</b></h4>
                </div>
                <div class="panel-footer">
                    <h4><b>Rules and site conventions</b></h4>
                    <p>Before you post, please keep in mind the following:</p>
                    <p> 1) Search to see if your question has already been asked
                    </p>
                    <p> 2) Keep it relevant to academic advising </p>
                    <p> 3) No spam, mean comments, or otherwise inappropriate content. (To report a post, email qashew.forum@gmail.com) </p>
                    <p> 4) <a href="/privacy">Privacy policy</a> </p>
                </div>
            </div>
            <!-- container for search and trending tags -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div>
                        <%= form_tag(questions_path, method: :get, class:"form-horizontal") do %>
                            <%= text_field_tag :term, params[:term], style:"width:80%", class:"form-control col-sm-6", placeholder: "Search by keyword, tag..." %>
                            <%= button_tag(:type => 'submit', style:"float:right;", :class => 'btn btn-default col-sm-2') do %>
                                    <span class="glyphicon glyphicon-search"></span>
                            <% end %>
                        <% end %>
                    </div>
                    <br><br>   
                </div>
                <div class="panel-footer">
                    <h4><b>Trending tags</b></h4>
                        <div id='tag_cloud'>
                          <% tag_cloud Question.tag_counts, %w{h5 h4 h3 h2} do |tag, css_class| %>
                              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
                          <% end %>
                        </div>
                </div>
            </div>
    	</div>
    </div>
</body>

app/views/questions/index.html.erb
<body>
    <%= render '/layouts/nav' %>
    <div class="container">
        <!-- left hand side layout -->
        <div class="col-md-8">
            <% if flash[:notice] or flash[:alert] %>
                    <div class="alert alert-dismissible alert-info" style="padding-top:10px;padding-bottom:10px">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <span class="notice"><%= flash[:notice] %></span>
                        <span class="alert"><%= flash[:alert] %></span>
                    </div>
            <% end %>
            <div class="panel panel-default"> 
                <div class="panel-body">
                    <!-- display questions -->
                    <div class="row">
                    	<div class="col-md-6">
                            <h3> <small><a href="/" style="text-decoration:none;color:darkgrey"><span class="glyphicon glyphicon-th-list"></span></a></small> <b>Questions</b></h3>
                            <br>
                        </div>
                        <br>
                        <div class="col-md-6">
                            <div class="btn-group pull-right">
                                <div class="btn-group dropdown">
                                          <button class="btn btn-default" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            View    
                                            <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
                                            
                                          </button>
                                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <li><%= link_to "All", :term => @search_term, :sort => "cached_weighted_score", class:"dropdown-item" %></li>
                                            <li><%= link_to "Most Upvotes", :term => @search_term, :sort => "cached_weighted_score", class:"dropdown-item" %></li>
                                            <li><%= link_to "Most Recent", :term => @search_term, :sort => "created_at", class:"dropdown-item" %></li>
                                            <li><%= link_to "Starred", :term => @search_term, :sort => "cached_weighted_score", :starred=>true, class:"dropdown-item" %></li>
                                          </ul>
                                </div>
                                <div class="btn-group">
                                      <%= link_to 'New Question', new_question_path, class: "btn btn-info"%>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <% if @search_term %>
                            Showing search results for "<%= @search_term %>"
                            <%= link_to 'Clear', questions_path %>
                        <% end %>
                    </div>
                    <br>
                	<table class="table table-striped table-hover">
                	  <tbody>
                	    <% if @questions.each do |question| %>
                	      <tr>
                	        <td id="question_<%= question.id %>" style="position:relative; padding:5px">
                                <%= render(partial: 'questions/question', locals: {question: question})%>
                			</td>
                	      </tr>
                	    <% end.empty? %>
                        <% end %>
                	  </tbody>
                	</table>
                    <%= paginate @questions %>
                    <%= page_entries_info @questions %>
                </div>
            </div>
        </div>

        <!-- right hand side layout -->
        <div class="col-md-4"> 
            <!-- container for user info -->
            <div class="panel panel-default">
                <br>
                <div class="panel-body">
                    <h4>Welcome, <b><%= current_user.username %>@</b></h4>
                </div>
                <div class="panel-footer">
                    <h4><b>Rules and site conventions</b></h4>
                    <p>Before you post, please keep in mind the following:</p>
                    <p> 1) Search to see if your question has already been asked
                    </p>
                    <p> 2) Keep it relevant to academic advising </p>
                    <p> 3) No spam, mean comments, or otherwise inappropriate content. (To report a post, email qashew.forum@gmail.com) </p>
                    <p> 4) <a href="/privacy">Privacy policy</a> </p>
                </div>
            </div>
            <!-- container for search and trending tags -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div>
                        <%= form_tag(questions_path, method: :get, class:"form-horizontal") do %>
                            <%= text_field_tag :term, params[:term], style:"width:80%", class:"form-control col-sm-6", placeholder: "Search by keyword, tag..." %>
                            <%= button_tag(:type => 'submit', style:"float:right;", :class => 'btn btn-default col-sm-2') do %>
                                    <span class="glyphicon glyphicon-search"></span>
                            <% end %>
                        <% end %>
                    </div>
                    <br><br>   
                </div>
                <div class="panel-footer">
                    <h4><b>Trending tags</b></h4>
                        <div id='tag_cloud'>
                          <% tag_cloud Question.tag_counts, %w{h5 h4 h3 h2} do |tag, css_class| %>
                              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
                          <% end %>
                        </div>
                </div>
            </div>
    	</div>
    </div>
</body>

app/views/questions/new.html.erb
<body>
    <%= render '/layouts/nav' %> 
    <div class="container"> 
    	<!-- left hand side layout -->
    	<div class="col-md-8 panel panel-default"> 
    	    <br>
    		<span class="glyphicon glyphicon-hand-left" aria-hidden="true"></span>
    		      <%= link_to 'Back', questions_path %>

    		<h3><b>New Question</b></h3>

    		<%= render 'form', question: @question %>
    		<br>
        </div>

        <!-- right hand side layout -->
        <div class="col-md-4"> 
          <!-- container for user info -->
            <div class="panel panel-default">
                <br>
                <div class="panel-body">
                    <h4>Welcome, <b><%= current_user.username %>@</b></h4>
                </div>
                <div class="panel-footer">
                    <h4><b>Rules and site conventions</b></h4>
                    <p>Before you post, please keep in mind the following:</p>
                    <p> 1) Search to see if your question has already been asked
                    </p>
                    <p> 2) Keep it relevant to academic advising </p>
                    <p> 3) No spam, mean comments, or otherwise inappropriate content. (To report a post, email qashew.forum@gmail.com) </p>
                    <p> 4) <a href="/privacy">Privacy policy</a> </p>
                </div>
            </div>
            <!-- container for search and trending tags -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div>
                        <%= form_tag(questions_path, method: :get, class:"form-horizontal") do %>
                            <%= text_field_tag :term, params[:term], style:"width:80%", class:"form-control col-sm-6", placeholder: "Search by keyword, tag..." %>
                            <%= button_tag(:type => 'submit', style:"float:right;", :class => 'btn btn-default col-sm-2') do %>
                                    <span class="glyphicon glyphicon-search"></span>
                            <% end %>
                        <% end %>
                    </div>
                    <br><br>   
                </div>
                <div class="panel-footer">
                    <h4><b>Trending tags</b></h4>
                        <div id='tag_cloud'>
                          <% tag_cloud Question.tag_counts, %w{h5 h4 h3 h2} do |tag, css_class| %>
                              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
                          <% end %>
                        </div>
                </div>
            </div>
      	</div>
    </div>
</body>

app/views/questions/resolved.js.erb
$("#question_shown").html("<%= escape_javascript(render partial: "questions/showquestion", locals: {question: @question}) %>");

app/views/questions/star.js.erb
$("#question_<%= @question.id %>").html("<%= escape_javascript(render partial: "questions/question", locals: {question: @question}) %>");
$("#question_shown").html("<%= escape_javascript(render partial: "questions/showquestion", locals: {question: @question}) %>");

app/views/questions/undodownvote.js.erb
$("#question_<%= @question.id %>").html("<%= escape_javascript(render partial: "questions/question", locals: {question: @question}) %>");
$("#question_shown").html("<%= escape_javascript(render partial: "questions/showquestion", locals: {question: @question}) %>");

app/views/questions/undoupvote.js.erb
$("#question_<%= @question.id %>").html("<%= escape_javascript(render partial: "questions/question", locals: {question: @question}) %>");
$("#question_shown").html("<%= escape_javascript(render partial: "questions/showquestion", locals: {question: @question}) %>");

app/views/questions/unstar.js.erb
$("#question_<%= @question.id %>").html("<%= escape_javascript(render partial: "questions/question", locals: {question: @question}) %>");
$("#question_shown").html("<%= escape_javascript(render partial: "questions/showquestion", locals: {question: @question}) %>");

app/views/questions/upvote.js.erb
$("#question_<%= @question.id %>").html("<%= escape_javascript(render partial: "questions/question", locals: {question: @question}) %>");
$("#question_shown").html("<%= escape_javascript(render partial: "questions/showquestion", locals: {question: @question}) %>");