config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/link_through'
  	get '/home' => 'pages#home'
  	get '/index' => 'questions#index'
  	get '/privacy' => "pages#privacy"
	get '/user/:id' => 'pages#profile'
	get '/tag/:tag_id' => 'pages#tag', as: :tag
	get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
	get 'notifications/:id/view_all', to: 'notifications#view_all',
								        as: :view_all

	devise_for :users

	resources :questions do
	  	resources :answers
		put "upvote", to: "questions#upvote"
		put "downvote", to: "questions#downvote"
		put "undoupvote", to: "questions#undoupvote"
		put "undodownvote", to: "questions#undodownvote"
		put "star", to: "questions#star"
		put "unstar", to: "questions#unstar"
		put "resolved", to: "questions#resolved"
	end

	resources :answers do
		resources :questions
		put "upvote", to: "answers#upvote"
		put "downvote", to: "answers#downvote"
		put "undoupvote", to: "answers#undoupvote"
		put "undodownvote", to: "answers#undodownvote"
	end

  	# define the root to go to questions if user is signed in, home otherwise
	authenticated :user do
	  root :to => "questions#index"
	end
	root :to => redirect("/home")
	# catch any undefined routes and redirect to root page
	
	get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :question

  validates :user_id, :notified_by_id, :question_id, :identifier, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

	def index
	  @notifications = current_user.notifications.page(params[:page]).per(20)
    end

	def link_through
		@notification = Notification.find(params[:id])
		@all = Notification.where('question_id'=> @notification.question_id, 'user_id' => current_user)
		@all.each do |n|
		    n.update read:true
	    end
		redirect_to question_path @notification.question
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li style="display:inline;">
  	<div style="margin-left:20px; margin-right:20px; margin-top:1px; margin-bottom:1px">
	  	<% if notification.notice_type == 'answered' %>
		  	<% if Answer.find_by_id(notification.identifier).anon %>
			  	<%= link_to "Anonymous #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%> 
		  	<% else %>
		  		<%= link_to "#{notification.notified_by.username} #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%>
		  	<% end %>
		  	<br> 
		  	<span class="text-muted" style="text-align:left;"><b><%=Question.find_by_id(notification.question_id).headline.truncate(40)%></b>
		  	<br>
		  	<span class="text-muted" style="text-align:left;"><i><%=Answer.find_by_id(notification.identifier).content.truncate(40)%></i>
	  	<% else %>
		  	<% if Question.find_by_id(notification.question_id).anon %>
			  	<%= link_to "Anonymous #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%> 
		  	<% else %>
		  		<%= link_to "#{notification.notified_by.username} #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%>
		  	<% end %>
		  	<br> 
		  	<span class="text-muted" style="text-align:left;"><b><%=Question.find_by_id(notification.question_id).headline.truncate(40)%></b>
		  	<br>
		  	<span class="text-muted" style="text-align:left;"><i><%=Question.find_by_id(notification.question_id).content.truncate(40)%></i>
	  	<% end %>
	</div>
</li>
 <li class="divider"></li>

app/views/notifications/_notification_dropdown.html.erb
<% if current_user.notifications.where(read:false).count > 0 %>
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="font-size:16px;">
		<span style="color:#db554e"><%= current_user.notifications.where(read:false).count%>
			<span class="glyphicon glyphicon-flag"></span>
		</span>
	</a>
	<ul class="dropdown-menu" style="width:325px">
	    <%= render current_user.notifications.where(read: false).order('created_at DESC').first(5)%>
	      <li class="text-center"><%= link_to "View All", "/user/#{current_user.username}" %></li>
	</ul>
<% else %>
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="font-size:16px;">
		0 <span class="glyphicon glyphicon-flag"></span>
	</a>
	<ul class="dropdown-menu" style="width:300px">
		<li class="text-center text-muted" style="font-size:15px"> No new notifications </li>
		<li class="divider"></li>
	    <li class="text-center"><%= link_to "View All", "/user/#{current_user.username}" %></li>
	</ul>
<% end %>

app/views/notifications/_notification_feed.html.erb
<li style="margin-top: 1em; background-color: white; padding: 1em;">
	  	<% if notification.notice_type == 'answered' %>
		  	<% if Answer.find_by_id(notification.identifier).anon %>
			  	<%= link_to "Anonymous #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%> 
		  	<% else %>
		  		<%= link_to "#{notification.notified_by.username} #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%>
		  	<% end %>
		  	<br> 
		  	<span class="text-muted" style="text-align:left;"><b><%=Question.find_by_id(notification.question_id).headline.truncate(60)%></b>
		  	<br>
		  	<span class="text-muted" style="text-align:left;"><i><%=Answer.find_by_id(notification.identifier).content.truncate(70)%></i>
	  	<% else %>
		  	<% if Question.find_by_id(notification.question_id).anon %>
			  	<%= link_to "Anonymous #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%> 
		  	<% else %>
		  		<%= link_to "#{notification.notified_by.username} #{notification.notice_type}", link_through_path(notification)%> <%="#{time_ago_in_words(notification.created_at)} ago"%>
		  	<% end %>
		  	<br> 
		  	<span class="text-muted" style="text-align:left;"><b><%=Question.find_by_id(notification.question_id).headline.truncate(60)%></b>
		  	<br>
		  	<span class="text-muted" style="text-align:left;"><i><%=Question.find_by_id(notification.question_id).content.truncate(70)%></i>
	  	<% end %>
 </li>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>