config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/link_through'
  	get '/home' => 'pages#home'
  	get '/index' => 'questions#index'
  	get '/privacy' => "pages#privacy"
	get '/user/:id' => 'pages#profile'
	get '/tag/:tag_id' => 'pages#tag', as: :tag
	get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
	get 'notifications/:id/view_all', to: 'notifications#view_all',
								        as: :view_all

	devise_for :users

	resources :questions do
	  	resources :answers
		put "upvote", to: "questions#upvote"
		put "downvote", to: "questions#downvote"
		put "undoupvote", to: "questions#undoupvote"
		put "undodownvote", to: "questions#undodownvote"
		put "star", to: "questions#star"
		put "unstar", to: "questions#unstar"
		put "resolved", to: "questions#resolved"
	end

	resources :answers do
		resources :questions
		put "upvote", to: "answers#upvote"
		put "downvote", to: "answers#downvote"
		put "undoupvote", to: "answers#undoupvote"
		put "undodownvote", to: "answers#undodownvote"
	end

  	# define the root to go to questions if user is signed in, home otherwise
	authenticated :user do
	  root :to => "questions#index"
	end
	root :to => redirect("/home")
	# catch any undefined routes and redirect to root page
	
	get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  acts_as_votable

  belongs_to :question
  belongs_to :user
  validates :user_id, presence: true
	validates :content, presence: true
	default_scope -> {order(:cached_weighted_score => :desc)}

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  	helper_method :create_notification

	def new
		@answer = Answer.new
	end

	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.create(answer_params)
		@answer.user = current_user
		@answer.qualifications = params[:answer][:qualifications]
		@answer.anon = params[:anon]
		if @answer.save
			create_notification @question, @answer
			AnswersMailer.answer_notification(@answer, @question, current_user).deliver
			flash[:notice] = "Thanks for answering!"
			redirect_to question_path(@question)
		else
			redirect_to question_path(@question), notice: "Your answer wasn't posted."
		end
	end

	def upvote
	    @question = Question.find(params[:question_id])
        @answer = @question.answers.find(params[:answer_id])
	    @answer.upvote_from current_user
        respond_to do |format|
	      format.js
	    end
  	end

    def downvote
        @question = Question.find(params[:question_id])
        @answer = @question.answers.find(params[:answer_id])
        @answer.downvote_from current_user
        respond_to do |format|
	      format.js
	    end
    end

    def undoupvote
        @question = Question.find(params[:question_id])
        @answer = @question.answers.find(params[:answer_id])
        @answer.unliked_by current_user
        respond_to do |format|
	      format.js
	    end
    end

    def undodownvote
        @question = Question.find(params[:question_id])
        @answer = @question.answers.find(params[:answer_id])
        @answer.undisliked_by current_user
        respond_to do |format|
	      format.js
	    end
    end

	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id])
	    @answer.destroy
	    respond_to do |format|
	      format.html { redirect_to question_path(@question), notice: 'Answer was successfully deleted.' }
	      format.json { head :no_content }
	    end
  	end

	def answer_params
      params.require(:answer).permit(:content, :qualifications, :anon)
    end

    private
    def create_notification(question, answer)
		return if question.user.id == current_user.id 
	    Notification.create(user_id: question.user_id,
	                        notified_by_id: current_user.id,
	                        question_id: question.id,
				            identifier: answer.id,
	                        notice_type: 'answered')
	    @selected = User.where("?=ANY(starred)", question.id)
	    @selected.each do |selected|
	    	if selected.id != current_user.id and selected.id != question.user.id
		    	Notification.create(user_id: selected.id,
		                        notified_by_id: current_user.id,
		                        question_id: question.id,
					            identifier: answer.id,
		                        notice_type: 'answered')
		    end
	    end
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<!-- right div: up/down arrows -->
<div style="float:right">
    <div> <!-- up arrow -->
                    <% if current_user.voted_up_on? answer %>
                        <button class="btn btn-default btn-xs" disabled="true">
                         <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> 
                         </button>  
                    <% else %>
                        <% if current_user.voted_down_on? answer %>
                            <%= button_to answer_undodownvote_path(:question_id => answer.question_id, :answer_id => answer.id), class:"btn btn-default btn-xs", method: :put, remote: true do %>
                             <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>   
                            <% end %>           
                        <% else %>
                            <%= button_to answer_upvote_path(:question_id => answer.question_id, :answer_id => answer.id), class:"btn btn-default btn-xs", method: :put, remote: true do %>
                             <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>   
                            <% end %>
                        <% end %>
                    <% end %>
                </div>

                <!-- current ranking -->
                <div class="text-center" style="line-height: 20px;height: 20px;">
                    <%= answer.weighted_score %>
                </div>
                <div> <!-- down arrow -->
                    <% if current_user.voted_down_on? answer %>
                        <button class="btn btn-default btn-xs" disabled="true">
                            <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                        </button>   
                    <% else %>
                        <% if current_user.voted_up_on? answer %>
                            <%= button_to answer_undoupvote_path(:question_id => answer.question_id, :answer_id => answer.id), class:"btn btn-default btn-xs", method: :put, remote: true do %>
                                <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>   
                            <% end %>           
                        <% else %>
                            <%= button_to answer_downvote_path(:question_id => answer.question_id, :answer_id => answer.id), class:"btn btn-default btn-xs", method: :put, remote: true do %>
                                <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>   
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
         </div>
            
<!-- left div: answer -->
<div>
    <!-- display username -->
 	<span style="font-size:16px">
        <b>
            <% if answer.anon %>
                Anonymous
            <% else %>
                <%= User.find_by_id(answer.user_id).username if User.find_by_id(answer.user_id)%>
            <% end %>
        </b>
        <% if answer.qualifications %>
            <i>, <%= answer.qualifications %></i>
        <% end %>
 	<br>	
     <!-- display how long ago the answer was created-->
	<div class="grey-text" style="font-size: 12px;">
        Answered
	    <% if answer.created_at > Time.now.beginning_of_day %>
	        <%="#{time_ago_in_words(answer.created_at)} ago"%> 
	    <% else %>
	        <%= answer.created_at.strftime("%b %d, %Y") %> 
	    <% end %>
	</div>

    <!-- display content -->
   	<%= answer.content %>
    <div> 
        <% if current_user.id == answer.user_id %>
            <%= link_to 'Delete', question_answer_path(answer.question_id, answer.id), method: :delete, data: {confirm: "Are you sure?"}, style:"font-size:14px" %>
        <% end %>
    </div>
    <hr />
</div>

app/views/answers/downvote.js.erb
$("#answer<%= @answer.id %>").html("<%= escape_javascript(render partial: "answers/answer", locals: {answer: @answer}) %>");

app/views/answers/undodownvote.js.erb
$("#answer<%= @answer.id %>").html("<%= escape_javascript(render partial: "answers/answer", locals: {answer: @answer}) %>");

app/views/answers/undoupvote.js.erb
$("#answer<%= @answer.id %>").html("<%= escape_javascript(render partial: "answers/answer", locals: {answer: @answer}) %>");

app/views/answers/upvote.js.erb
$("#answer<%= @answer.id %>").html("<%= escape_javascript(render partial: "answers/answer", locals: {answer: @answer}) %>");