config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/link_through'
  	get '/home' => 'pages#home'
  	get '/index' => 'questions#index'
  	get '/privacy' => "pages#privacy"
	get '/user/:id' => 'pages#profile'
	get '/tag/:tag_id' => 'pages#tag', as: :tag
	get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
	get 'notifications/:id/view_all', to: 'notifications#view_all',
								        as: :view_all

	devise_for :users

	resources :questions do
	  	resources :answers
		put "upvote", to: "questions#upvote"
		put "downvote", to: "questions#downvote"
		put "undoupvote", to: "questions#undoupvote"
		put "undodownvote", to: "questions#undodownvote"
		put "star", to: "questions#star"
		put "unstar", to: "questions#unstar"
		put "resolved", to: "questions#resolved"
	end

	resources :answers do
		resources :questions
		put "upvote", to: "answers#upvote"
		put "downvote", to: "answers#downvote"
		put "undoupvote", to: "answers#undoupvote"
		put "undodownvote", to: "answers#undodownvote"
	end

  	# define the root to go to questions if user is signed in, home otherwise
	authenticated :user do
	  root :to => "questions#index"
	end
	root :to => redirect("/home")
	# catch any undefined routes and redirect to root page
	
	get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/explore.html.erb
<h1>Pages#explore</h1>
<p>Find me in app/views/pages/explore.html.erb</p>

app/views/pages/home.html.erb
<body>
	<%= render '/layouts/nav_guest' %>

    <section class="jumbotron text-center" style="background-image: url('paper_fibers.png');height:200%;margin-bottom:0;">
	  	<div class="container-fluid">
			<div class="row">
				<div class="col-md-6 col-md-offset-3"> 
				    <h1 style="font-size: 70px;"><b>Q<span style="font-size:45px;"><sup>+</sup></span>A</b>shew
				    <img src="cashew.png" alt="Cashew" style="width:15%; height:15%;"></h1>
				    <p class="lead text-muted" style="font-size:30px;">
					    a campus forum for academic advising <br>
					    created for students, by students
					</p>
					<br>
					<div class="col-md-8 col-md-offset-2">
						<div class="panel panel-default">
						    <div class="panel-heading" style="background-color: #ededed">
						        <h3 class="panel-title text-center">Sign up</h3>
						    </div>
						    <div class="panel-body">
						        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
							        <%= devise_error_messages! %>
								    <div class="form-group">
								        <%= f.label :email, "University email address" %><br />
								        <%= f.email_field :email, class:"form-control", placeholder:"netid@princeton.edu" %>
								    </div>

								    <div class="form-group">
								        <%= f.label :password %>
								        <% if @minimum_password_length %>
								        <em>(<%= @minimum_password_length %> characters minimum)</em>
								        <% end %><br />
								        <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder:"Create a password"%>
								    </div>

								    <div class="form-group">
								        <%= f.label :password_confirmation %><br />
								        <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control", placeholder:"Re-enter your password"%>
								    </div>
								    <div class="actions">
								        <%= f.submit "Join the community", class:"btn btn-success btn-block" %>
								    </div>
							    <% end %>
						    </div>
					    </div>
					</div>
			    </div>
			</div>
		</div>
	</section>

	<!-- About Section -->
    <section id="about" class="content-section text-left" style="background-image: url('stardust.png')">
      <div class="container">
        <div class="row" style="margin-top:100px;margin-bottom:100px">
          <div class="col-md-8 col-md-offset-1">
          	<h1 style="color:#e2e2e2">Q<span style="font-size:20px;"><sup>+</sup></span>Ashew <span style="font-size:30px">[<i>cash</i>·ew] is a platform that leverages the collective expertise of the student body to help students make better-informed decisions about course selection, deciding on a major, and more.</span></h1>
          </div>
          <div class="col" style="margin-top:25px">
          	<img src="004-column.png" alt="School" style="width:15%; height:15%;">
          </div>
        </div>
      </div>
    </section>
    <!-- About Section -->
    <section id="about" class="content-section text-center" style="background-image: url('paper_fibers.png')">
      <div class="container">
        <div class="row" style="margin-top:75px;margin-bottom:75px">
        	<h2>Features</h2> <br>
	        <div class="col-md-5 text-left">
	          	<h3><i>Campus-specific</i></h3>
	          	<h4 class="text-muted">University email recognition means the forum is restricted to students on your campus</h4>
	          	<h3><i>Ask and answer candidly</i></h3>
	          	<h4 class="text-muted">Submit anonymously. Or show your netid - you choose</h4>
	          	<h3><i>Up-down voting</i></h3>
	          	<h4 class="text-muted">Voting allows users to self-monitor content and makes it possible for the hottest questions and answers to rise to the top</h4>
	          	<h3><i>Tagging system</i></h3>
	          	<h4 class="text-muted">Identify which departments your questions belong to, and track the topics that matter to you</h4>
	          	<h3><i>Reputability</i></h3>
	          	<h4 class="text-muted">Taglines let you explain why you're qualified to answer</h4>
	        </div>
	        <div class="col" style="margin-top:75px">
	          	<img src="screenshot.png" alt="School" style="width:55%; height:55%;">
	        </div>
        </div>
      </div>
    </section>


<!--Footer-->
<footer class="page-footer center-on-small-only blue-grey lighten-5 pt-0">

    <div style="background-color: #18a573;">
        <div class="container">
            <!--Grid row-->
            <div class="row py-4 d-flex align-items-center">
                <!--Grid column-->
                <div class="text-center" style="height:50px">
                    <h3 class="text-center text-md-left" style="color:white;margin:20px"><strong><%= link_to('Sign Up Now', new_user_registration_path, style:"text-decoration:none;color:white") %> <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> </strong></h3>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </div>
    </div>

    <!--Footer Links-->
    <div class="container text-center">
        <div class="row" style="padding-top:20px;padding-bottom:20px">
            <!--First column-->
            <div class="col-md-4 text-left">
                <h2 class="title font-bold"><strong>
                	Q<span style="font-size:25px;"><sup>+</sup></span>A</b>shew
				    <img src="cashew.png" alt="Cashew" style="width:15%; height:15%;">
                </strong></h2>
                <p class="lead text-muted" >
					    a campus forum for academic advising <br>
				</p>
				<p>
					<a href="/privacy">Privacy policy</a>
				</p>
            </div>
            <!--/.First column-->

            <!--Second column-->
            <div class="col-md-4">
                <h4 class="title" style="margin-top:25px"><strong>Developed by</strong></h4>
                <hr style="width: 60px;">
                <p>Casey Li (caseyli@)</p>
                <p>Princeton Computer Science '19</p>
                <p>Junior Independent Work Fall 2017</p>
                <p>COS IW05: Invention and Innovation </p>
            </div>
            <!--/.Second column-->

            <!--Third column-->
            <div class="col-md-4 dark-grey-text">
            	<h4 class="title" style="margin-top:25px"><strong>Acknowledgements</strong></h4>
            	<hr style="width: 60px;">
            	<p>Professor Robert Fish </p>
            	<p>Preceptor Mikhail Khodak </p>
            	<p>Many thanks to my COS IW05 classmates!</p>
            	<p style="color:#bcbcbc">Icons made by Freepik from www.flaticon.com</p>
            </div>
            <!--/.Third column-->
        </div>
    </div>
    <!--/.Footer Links-->
    
</footer>
<!--/.Footer-->

</body>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/privacy.html.erb
<body>  
	<nav class="navbar navbar-default">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="container" style="padding-left:50%">
	      <%= link_to(image_tag("cashew.png", :alt => "logo", :title => "Home", :class=>"text-center",:style=>"width:13%;height:13%;padding:10px;margin-left: -30px;float:none"), "/") %>
	    </div>
	</nav>

    <div class="container"> 
    	<!-- left hand side layout -->
    	<div class="col-md-6 col-md-offset-3 text-center"> 
    	    <h4><b>Privacy Policy</b></h4>
            <p>
				Q+Ashew saves your university email to create and identify your unique account. It also saves information about your submitted content and questions that you've starred, so that you can reference these later. </p>
			<p>
				In the event that a post is reported and deemed as inappropriate, it will be removed.  
			</p>
			<p> 
				Data is stored securely and can only be accessed by the site administrator. 
			</p> 
			<p>
				You may email qashew.forum@gmail.com with any further questions. <br>If you do not consent to the privacy policy, please refrain from using this service.
            </p>
        </div>
    </div>
</body>

app/views/pages/profile.html.erb
<body>  
    <%= render '/layouts/nav' %>

    <div class="container"> 
    	<!-- left hand side layout -->
    	    <h3><b>Notifications</b></h3>
            <ul style="list-style:none; margin:0;padding:0;">
                <%= render :partial => "notifications/notification_feed", :collection => @notifications, :as => :notification  %>
            </ul>

                    <%= paginate @notifications %>
                    <%= page_entries_info @notifications %>
    </div>

</body>

app/views/pages/tag.html.erb
<body>
        <%= render '/layouts/nav' %>

    <div class="container">
        <!-- left hand side layout -->
        <div class="col-md-8 panel panel-default"> 
            <!-- display questions -->
            <div class="row">
                <div class="col-md-6">
                    <h3> <small><a href="/" style="text-decoration:none;color:darkgrey"><span class="glyphicon glyphicon-th-list"></span></a></small> <b>Questions</b></h3>
                </div>
                <br>
                <div class="col-md-6">
                    <div class="btn-group pull-right">
                        <div class="btn-group dropdown">
                                  <button class="btn btn-default" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Sort by
                                    <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
                                    
                                  </button>
                                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li><%= link_to "Most Upvoted", :term => @search_term, :sort => "cached_weighted_score", class:"dropdown-item" %></li>
                                    <li><%= link_to "Newest", :term => @search_term, :sort => "created_at", class:"dropdown-item" %></li>
                                  </ul>
                        </div>
                        <div class="btn-group">
                              <%= link_to 'New Question', new_question_path, class: "btn btn-info"%>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="col">
                <% if @search_term %>
                    <div>
                        Showing search results for "<%= @search_term %>"
                        <%= link_to 'Clear', tag_path(@tag) %>
                    </div>
                <% end %>
                <% if @tag %>
                    <div>
                        Filtering by tag: 
                        <span class="label label-info">
                            <%= @tag %>
                            <small><a href="/" class="glyphicon glyphicon-remove-sign"></a></small>
                        </span>
                    </div>
                <% end %>
            </div>
            <br>
            <table class="table table-striped table-hover">
              <tbody>
                <% if @questions.each do |question| %>
                  <tr>
                    <td id="question_<%= question.id %>" style="position:relative; padding:5px">
                        <%= render(partial: 'questions/question', locals: {question: question})%>
                    </td>
                  </tr>
                <% end.empty? %>
                  <h5>Sorry, there are no questions here.</h5>
                <% end %>
              </tbody>
            </table>
            <br>
        </div>

        <!-- right hand side layout -->
        <div class="col-md-4"> 
            <!-- container for user info -->
            <div class="panel panel-default">
                <br>
                <div class="panel-body">
                    <h4>Welcome, <b><%= current_user.username %>@</b></h4>
                </div>
                <div class="panel-footer">
                    <h4><b>Rules and site conventions</b></h4>
                    <p>Before you post, please keep in mind the following:</p>
                    <p> 1) Search to see if your question has already been asked
                    </p>
                    <p> 2) Keep it relevant to academic advising </p>
                    <p> 3) No spam, mean comments, or otherwise inappropriate content. (To report a post, email qashew.forum@gmail.com) </p>
                    <p> 4) <a href="/privacy">Privacy policy</a> </p>
                </div>
            </div>
            <!-- container for search and trending tags -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div>
                        <%= form_tag(questions_path, method: :get, class:"form-horizontal") do %>
                            <%= text_field_tag :term, params[:term], style:"width:80%", class:"form-control col-sm-6", placeholder: "Search by keyword, tag..." %>
                            <%= button_tag(:type => 'submit', style:"float:right;", :class => 'btn btn-default col-sm-2') do %>
                                    <span class="glyphicon glyphicon-search"></span>
                            <% end %>
                        <% end %>
                    </div>
                    <br><br>   
                </div>
                <div class="panel-footer">
                    <h4><b>Trending tags</b></h4>
                        <div id='tag_cloud'>
                          <% tag_cloud Question.tag_counts, %w{h5 h4 h3 h2} do |tag, css_class| %>
                              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
                          <% end %>
                        </div>
                </div>
            </div>
        </div>
    </div>
</body>